name: Deploy to EC2 with Terraform & Docker.

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Terraform init
        run: terraform init

     
      - name: Terraform apply
        run: terraform apply -auto-approve

 

      # Set environment variable for EC2 IP in frontend's .env
      

      - name: Build Docker images
        run: |
          docker build -t my-frontend -f frontend/Dockerfile.frontend frontend
          docker build -t my-backend -f backend/Dockerfile.backend backend

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker images
        run: |
          docker tag my-frontend ameni1717/my-frontend:latest
          docker tag my-backend ameni1717/my-backend:latest
          docker push ameni1717/my-frontend:latest
          docker push ameni1717/my-backend:latest
     
      - name: Deploy to EC2 via SSH
        run: |
          # Set up SSH
          
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_PRIVATE_KEY}}" > ~/.ssh/meinPrivateKey
          chmod 600 ~/.ssh/meinPrivateKey
          


          # SSH into the EC2 instance and deploy Docker containers
        
          ssh -i  ~/.ssh/meinPrivateKey -o StrictHostKeyChecking=no ubuntu@18.199.237.221 << 'ENDSSH'
            sudo apt update -y
            sudo apt upgrade -y
            sudo apt install docker -y
            sudo systemctl enable docker.service
            sudo systemctl start docker
            sudo usermod -aG docker ubuntu
            docker pull ameni1717/my-frontend:latest
            docker pull ameni1717/my-backend:latest
            docker run -d -p 80:80 --name frontend my-frontend
            docker run -d -p 3001:3001 --name backend my-backend
          ENDSSH
